python train.py --data_dir dataset/milcause_bert \
--transformer_type bert \
--model_name_or_path models/bert-base-chinese \
--train_file train_annotated.json \
--dev_file dev.json \
--test_file test.json \
--train_batch_size 32 \
--test_batch_size 32 \
--gradient_accumulation_steps 1 \
--num_labels 1 \
--learning_rate 5e-5 \
--max_grad_norm 1.0 \
--warmup_ratio 0.06 \
--num_train_epochs 30.0 \
--seed 66 \
--num_class 2
